// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  module.exports = {
    exec: function(hook, fact, cb) {
      var k, options;
      console.log((function() {
        var _results;
        _results = [];
        for (k in fact) {
          _results.push(k);
        }
        return _results;
      })(), fact.hook);
      options = {
        method: hook.options.method || 'POST',
        uri: "t.trakapo.com:2474/" + hook.options.subtype + "/exec",
        json: fact
      };
      return request.post(options, function(err, req, body) {
        return cb(err, body);
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=airgap.map
*/
