// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  module.exports = {
    exec: function(hook, fact, cb) {
      var options;
      console.log(fact);
      options = {
        method: hook.options.method || 'POST',
        uri: "http://t.trakapo.com:2474/" + hook.options.subtype + "/exec",
        json: fact
      };
      return request.post(options, function(err, req, body) {
        return cb(err, body);
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=airgap.map
*/
