// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  module.exports = {
    exec: function(hook, fact, cb) {
      var options;
      options = {
        method: hook.options.method || 'POST',
        uri: hook.options.url,
        json: fact
      };
      return request.post(options, function(err, req, body) {
        return cb(err, body);
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=url.map
*/
