// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(server) {
    server.get({
      path: '/',
      auth: false
    }, function(req, res, next) {
      res.suppressLog = req.suppressLog = true;
      return next(res.send({
        status: 'ok',
        statusText: 'Faction, a data processing API that you\'re not cool enough to use'
      }));
    });
    return server.get({
      path: '/ping',
      auth: false
    }, function(req, res, next) {
      res.suppressLog = req.suppressLog = true;
      return next(res.send({
        status: 'ok',
        statusText: 'pong',
        time: +(new Date)
      }));
    });
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
