// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(server) {
    server.get('/info/:info-type/mappings', Infomapping_Model.route, function(req, res, next) {
      return req.model.loadPaginated(req.params.asQuery(), req, ErrorHandler(next, function(err, response) {
        return res.send(response);
      }));
    });
    server.post('/info/:info-type/mappings/:mapping-id', Infomapping_Model.route, function(req, res, next) {
      var _this = this;
      delete req.body._id;
      req.body.info_type = req.params['info-type'];
      req.body.mapping_id = req.params['mapping-id'];
      return req.model.update(req.params.asQuery(), req.body, ErrorHandler(next, function(err, updated) {
        return res.send({
          status: 'ok',
          statusText: 'The information mapping was ' + (updated && 'updated.' || 'created.'),
          mapping: req.model["export"]()
        });
      }));
    });
    return server.del('/info/:info-type/mappings/:mapping-id', Infomapping_Model.route, function(req, res, next) {
      return req.model.remove(req.params.asQuery(), function(err, count) {
        return res.send({
          status: 'ok',
          statusText: 'The information mapping was deleted.',
          deleted: count | 0
        });
      });
    });
  };

}).call(this);
