// Generated by CoffeeScript 1.6.3
(function() {
  var async;

  async = require('async');

  module.exports = function(server) {
    return server.get('/export', Factsettings_Model.route, function(req, res, next) {
      var db, loadRows;
      db = req.model.db;
      loadRows = function(name, next) {
        return db.collection(name).find(function(err, cursor) {
          return cursor.toArray(function(err, res) {
            return next(err, [name, res]);
          });
        });
      };
      return async.map(['info_mappings', 'fact_settings', 'hooks'], loadRows, function(err, results) {
        var output, row, _i, _len;
        output = {};
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          row = results[_i];
          output[row[0]] = row[1];
        }
        res.header('Content-Description', 'File Transfer');
        res.header('Content-Type', 'text/json');
        res.header('Content-Disposition', 'attachment; filename=faction-export.json');
        return res.send(JSON.stringify(output));
      });
    });
  };

}).call(this);

/*
//@ sourceMappingURL=io.map
*/
