// Generated by CoffeeScript 1.6.3
var Q, deferredRequest, request;

Q = require('q');

request = require('request');

deferredRequest = function(method, url, body) {
  var defer, options;
  defer = Q.defer();
  options = {
    method: method.toUpperCase(),
    uri: url,
    json: body
  };
  request[method.toLowerCase()](options, function(err, response, body) {
    if (err || response.statusCode.toString().charAt(0) !== '2') {
      return defer.reject(err || 'Uknown error');
    }
    return defer.resolve(body);
  });
  return defer.promise;
};

module.exports = {
  get: function(url, body) {
    return deferredRequest('get', url, body);
  },
  post: function(url, body) {
    return deferredRequest('post', url, body);
  },
  put: function(url, body) {
    return deferredRequest('put', url, body);
  },
  patch: function(url, body) {
    return deferredRequest('patch', url, body);
  },
  "delete": function(url, body) {
    return deferredRequest('delete', url, body);
  }
};

/*
//@ sourceMappingURL=http.map
*/
