// Generated by CoffeeScript 1.6.3
var Fact_Model, Model, async,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

async = require('async');

Model = require('./model');

module.exports = Fact_Model = (function(_super) {
  __extends(Fact_Model, _super);

  function Fact_Model(account, type, callback) {
    this.account = account;
    this.type = type;
    this.type = type.replace(/[^a-z0-9_]+/g, '_').substring(0, 60);
    Fact_Model.__super__.constructor.call(this, account.dbname(), this.collectionname(), function(self, db, coll) {
      return callback.apply(this, arguments);
    });
  }

  Fact_Model.prototype._spawn = function(callback) {
    return new this.constructor(this.account, this.type, callback);
  };

  Fact_Model.collectionname = Fact_Model.prototype.collectionname = function(type) {
    if (type == null) {
      type = this.type;
    }
    return 'facts_' + type.replace(/[^a-z0-9_]+/g, '_').substring(0, 60);
  };

  Fact_Model.route = function(req, res, next) {
    if (req.params['fact-type']) {
      return new Fact_Model(req.account, req.params['fact-type'], function() {
        req.model = this;
        return next();
      });
    } else {
      return next();
    }
  };

  Fact_Model.prototype.removeFull = function(callback) {
    return this.table.drop(callback);
  };

  Fact_Model.prototype.load = function(query, shim, callback) {
    var args;
    args = Array.prototype.slice.call(arguments, 1);
    callback = args.pop();
    shim = args.pop() || false;
    return Fact_Model.__super__.load.call(this, query, callback);
  };

  Fact_Model.prototype.loadAll = function(query, shim, callback) {
    var args,
      _this = this;
    args = Array.prototype.slice.call(arguments, 1);
    callback = args.pop();
    shim = args.pop() || false;
    return this.table.find(query, {
      _id: 1
    }).toArray(function(err, ids) {
      var loader;
      loader = function(row, next) {
        return _this._spawn(function() {
          return this.load({
            _id: row._id
          }, shim, next);
        });
      };
      return async.map(ids, loader, callback);
    });
  };

  Fact_Model.getTypes = function(account, callback) {
    return mongodb.open(account.dbname(), function(err, db) {
      return db.collectionNames(function(err, collections) {
        var coll, len, result;
        len = db.databaseName.length + 1;
        result = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = collections.length; _i < _len; _i++) {
            coll = collections[_i];
            if ('facts_' === coll.name.substring(len, len + 5)) {
              _results.push(coll.name.slice(len + 5));
            }
          }
          return _results;
        })();
        result.detailed = function(callback) {
          var iter;
          iter = function(type, next) {
            return new Fact_Model(account, type, function() {
              return this.table.count(function(err, size) {
                return next(err, {
                  fact_type: type,
                  fact_sources: 'todo',
                  count: size,
                  nextPage: "/facts/" + type
                });
              });
            });
          };
          return async.map(result, iter, function(err, info) {
            var fact, obj, _i, _len, _ref;
            obj = {};
            _ref = info || [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              fact = _ref[_i];
              obj[fact.fact_type] = fact;
            }
            return callback(err, obj);
          });
        };
        return callback(err, result);
      });
    });
  };

  return Fact_Model;

})(Model);
