// Generated by CoffeeScript 1.6.3
(function() {
  var Cache, async;

  async = require('async');

  Cache = require('shared-cache');

  module.exports = {
    disabled: false,
    concurrency: 1,
    timeout: 10000,
    exec: function(job, done) {
      var account, accountID, query, time, type;
      account = null;
      accountID = job.data.account;
      time = new Date(parseInt(job.created_at));
      type = job.data.data.fact_type;
      query = job.data.data.query;
      return loadAccount(accountID, function(err, acc) {
        account = acc;
        return new Fact_deferred_Model(account, type, function(err) {
          return this.table.aggregate([
            {
              $match: query
            }, {
              $group: {
                _id: null,
                ids: {
                  $push: '$_id'
                }
              }
            }
          ], function(err, result) {
            var e, ids, insert,
              _this = this;
            try {
              ids = result[0].ids;
              insert = function(id, next) {
                return Fact_deferred_Model.markUpdated(id, type, accountID, next);
              };
              console.log('Fact_update_all creating ' + ids.length + ' jobs');
              return async.forEach(ids, insert, done);
            } catch (_error) {
              e = _error;
              return done(e);
            }
          });
        });
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
