// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    name: 'log',
    description: 'Simply log some information',
    validate: function(action, callback) {
      return callback();
    },
    exec: function(info, next) {
      console.log('@', info.step.log);
      return next(null, info.step.log);
    }
  };

}).call(this);
