// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    name: 'produce_info',
    description: 'Create new information to be mapped',
    validate: function(info, callback) {
      if (!info.action.type) {
        return callback('Must have a type');
      }
      return callback();
    },
    exec: function(info, next) {
      return info.fact.withMap([], info.action.map, function(err, result) {
        if (err) {
          return next(err);
        }
        return new Info_Model(info.fact.account, function() {
          return this.create(info.action.type, result, function(err) {
            return next(err, result);
          });
        });
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=produce_info.map
*/
