// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    name: 'wait',
    description: 'Delay the next step.',
    fields: {
      delay: 'The number of seconds to delay until the next step'
    },
    validate: function(info, callback) {
      var num;
      num = Number(info.step.delay || -1);
      if (isNaN(num) || num <= 0) {
        return callback('There must be a positive "delay" in number of seconds.');
      }
      return callback();
    },
    exec: function(info, next) {
      var obj;
      obj = JSON.parse(JSON.stringify(info.job));
      obj.title += " (D" + info.stage + ")";
      obj.data.stage = info.stage;
      jobs.create('perform_action', obj).delay(info.step.delay * 1000).save();
      return next({
        halt: true
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=wait.map
*/
