// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    exec: function(hook, fact, cb) {
      var options;
      console.log('URL', hook, fact);
      return;
      options = {
        method: 'POST',
        uri: hook.url,
        json: fact
      };
      return request.post(options, cb);
    }
  };

}).call(this);
