// Generated by CoffeeScript 1.6.3
module.exports = function(server) {
  server.get('/facts', function(req, res, next) {
    return Fact_Model.getTypes(req.account, function(types) {
      return types.detailed(function(info) {
        return res.send(info);
      });
    });
  });
  server.get('/facts/:fact-type', Fact_Model.route, function(req, res, next) {
    return req.model.loadPaginated(req.body, req, function(err, response) {
      if (err) {
        throw err;
      }
      return res.send(response);
    });
  });
  server.get('/facts/:fact-type/:fact-id', Fact_Model.route, function(req, res, next) {
    return req.model.load({
      _id: req.params['fact-id']
    }, function() {
      return res.send(this["export"]());
    });
  });
  server.post('/facts/:fact-type/:fact-id', Fact_Model.route, function(req, res, next) {
    req.body._id = req.params['fact-id'];
    return req.model.update({
      _id: req.params['fact-id']
    }, req.body, function(err, updated) {
      return res.send({
        status: 'ok',
        statusText: 'The fact was ' + (updated && 'updated.' || 'created.'),
        fact: this["export"]()
      });
    });
  });
  server.del('/facts/:fact-type', Fact_Model.route, function(req, res, next) {
    return req.model.removeFull(function() {
      return res.send({
        status: 'ok',
        statusText: 'All facts of this type have been deleted.'
      });
    });
  });
  return server.del('/facts/:fact-type/:fact-id', Fact_Model.route, function(req, res, next) {
    return req.model.remove({
      _id: req.params['fact-id']
    }, function(err, count) {
      return res.send({
        status: 'ok',
        statusText: 'The fact was deleted.',
        deleted: count | 0
      });
    });
  });
};
