// Generated by CoffeeScript 1.6.3
module.exports = function(server) {
  server.post('/info/:info-type', Info_Model.route, function(req, res, next) {
    return req.model.create(req.params['info-type'], req.body, function(err) {
      if (err) {
        throw err;
      }
      return res.send({
        status: 'ok',
        statusText: 'Information recieved'
      });
    });
  });
  server.get('/info/:info-type/handlers', Infohandler_Model.route, function(req, res, next) {
    var type;
    type = req.params['info-type'];
    return req.model.loadPaginated({
      info_type: type
    }, req, function(err, response) {
      if (err) {
        throw err;
      }
      return res.send(response);
    });
  });
  server.post('/info/:info-type/handler/:handler-id', Infohandler_Model.route, function(req, res, next) {
    var _this = this;
    req.body.handler_id = req.params['handler-id'];
    return req.model.create(req.params['info-type'], req.body, function(err) {
      if (err) {
        throw err;
      }
      return res.send({
        status: 'ok',
        statusText: 'The information handler was updated.',
        handler: _this["export"]()
      });
    });
  });
  return server.del('/info/:info-type/handler/:handler-id', Infohandler_Model.route, function(req, res, next) {
    return req.model.remove({
      _id: req.params['handler-id']
    }, function(err, count) {
      return res.send({
        status: 'ok',
        statusText: 'The information handler was deleted.',
        deleted: count | 0
      });
    });
  });
};
