// Generated by CoffeeScript 1.6.3
module.exports = function(server) {
  server.post('/info/:info-type', function(req, res, next) {
    return new Info_Model(req.account, function() {
      return this.create(req.params['info-type'], req.body, function(err) {
        if (err) {
          throw err;
        }
        return res.send({
          status: 'ok',
          statusText: 'Information recieved'
        });
      });
    });
  });
  server.get('/info/:info-type/handlers', function(req, res, next) {
    return new Infohandler_Model(req.account, function() {
      var type;
      type = req.params['info-type'];
      return this.loadPaginated({
        info_type: type
      }, req, function(err, response) {
        if (err) {
          throw err;
        }
        return res.send(response);
      });
    });
  });
  server.post('/info/:info-type/handler/:handler-id', function(req, res, next) {
    return new Infohandler_Model(req.account, function() {
      var e,
        _this = this;
      try {
        req.body._id = req.params['handler-id'];
        return this.create(req.params['info-type'], req.body, function(err) {
          if (err) {
            throw err;
          }
          return res.send({
            status: 'ok',
            statusText: 'The information handler was updated.',
            handler: _this["export"]()
          });
        });
      } catch (_error) {
        e = _error;
        return server.emit('uncaughtException', req, res, req.route, e);
      }
    });
  });
  return server.del('/info/:info-type/handler/:handler-id', function(req, res, next) {
    return new Infohandler_Model(req.account, function() {
      return this.remove({
        _id: req.params['handler-id']
      }, function(err, count) {
        return res.send({
          status: 'ok',
          statusText: 'The information handler was deleted.',
          deleted: count | 0
        });
      });
    });
  });
};
