// Generated by CoffeeScript 1.6.3
module.exports = function(stream, config, row) {
  var bindFunctions;
  bindFunctions = require('./bind_functions')(stream, config, row);
  return function(data, callback) {
    bindFunctions(data);
    return callback(null, data);
  };
  return addShim;
};
