// Generated by CoffeeScript 1.6.3
(function() {
  var wrapArray;

  module.exports = wrapArray = function(arr) {
    var k, keys, row, _i, _j, _len, _len1, _ref;
    if (!Array.isArray(arr)) {
      return arr;
    }
    keys = {};
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      row = arr[_i];
      if (Object.prototype.toString.call(row) === '[object Object]') {
        _ref = Object.keys(row);
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          k = _ref[_j];
          keys[k] = true;
        }
      }
    }
    Object.keys(keys).forEach(function(key) {
      var _this = this;
      return Object.defineProperty(arr, key, {
        get: function() {
          var result;
          result = wrapArray([].concat.apply([], arr.map(function(row) {
            return row[key];
          }).filter(Boolean)));
          return result;
        }
      });
    });
    return arr;
  };

}).call(this);
