// Generated by CoffeeScript 1.6.3
(function() {
  var bindFunctions;

  bindFunctions = require('./bind_functions');

  module.exports = function(data, callback) {
    bindFunctions(data);
    return callback(null, data);
  };

}).call(this);

/*
//@ sourceMappingURL=add_shim.map
*/
