// Generated by CoffeeScript 1.6.3
(function() {
  var traverse, url;

  traverse = require('traverse');

  url = require('url');

  module.exports = function(data) {
    traverse(data).forEach(function(value) {
      var obj;
      if (value && typeof value === 'string') {
        obj = url.parse(value, true);
        if (obj.pathname && obj.host) {
          if ((this.parent.node.pathname != null) && (this.parent.node.host != null)) {
            return;
          }
          return this.update(obj, true);
        }
      }
    });
    return data;
  };

  module.exports.unbind = function(data) {
    return traverse(data).forEach(function(value) {
      if (value.pathname && value.href) {
        return this.update(value.href, true);
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=bind_urls.map
*/
