// Generated by CoffeeScript 1.6.3
(function() {
  var traverse, url;

  traverse = require('traverse');

  url = require('url');

  module.exports = function() {
    if (!("http://www.google.com".host != null)) {
      return Object.keys(url.parse('')).forEach(function(key) {
        return Object.defineProperty(String.prototype, key, {
          get: function() {
            var value;
            value = url.parse(this.toString(), true)[key];
            console.log('  url', key, value);
            return value;
          }
        });
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=bind_urls.map
*/
