// Generated by CoffeeScript 1.6.3
(function() {
  var traverse, url;

  traverse = require('traverse');

  url = require('url');

  module.exports = function(data) {
    traverse(data).forEach(function(value) {
      var obj;
      if (value && typeof value === 'string') {
        obj = url.parse(value);
        if (obj.pathname && obj.host) {
          obj.toString = function() {
            return this.href;
          };
          obj.toJSON = function() {
            return this.toString();
          };
          return this.update(obj, true);
        }
      }
    });
    return data;
  };

}).call(this);

/*
//@ sourceMappingURL=bind_urls.map
*/
