// Generated by CoffeeScript 1.6.3
(function() {
  var deleteColumn, getColumn, setColumn, traverse, xtend, _ref;

  xtend = require('xtend');

  traverse = require('traverse');

  _ref = require('./column_ops'), getColumn = _ref.getColumn, setColumn = _ref.setColumn, deleteColumn = _ref.deleteColumn;

  module.exports = function(settings, old_fact, mid_fact) {
    var a, b, field, k, key, list, mode, new_fact, old_value, orig, sets, v, val, value, _ref1;
    if (settings.time == null) {
      settings.time = new Date;
    }
    if (old_fact == null) {
      old_fact = {};
    }
    if (mid_fact == null) {
      mid_fact = {};
    }
    sets = {};
    for (key in mid_fact) {
      val = mid_fact[key];
      if (((old_fact != null ? old_fact[key] : void 0) != null) && old_fact[key] === mid_fact[key]) {
        continue;
      }
      sets[key] = {
        type: '$set',
        value: val
      };
    }
    new_fact = xtend(old_fact, mid_fact);
    _ref1 = settings.field_modes;
    for (field in _ref1) {
      mode = _ref1[field];
      if (mode["eval"]) {
        continue;
      }
      value = mid_fact[field];
      old_value = old_fact[field];
      if (mode === 'inc') {
        a = Number(value) || 1;
        b = Number(old_value) || 0;
        sets[field] = {
          type: '$inc',
          value: a
        };
        setColumn(new_fact, field, a + b);
      }
      if (value) {
        if (mode === 'inc_map') {
          delete sets[field];
          value = value.replace(/\./g, '%2E');
          sets[field + '.' + value] = {
            type: '$inc',
            value: 1
          };
        }
        if (mode === 'all') {
          orig = old_value || [];
          if (!Array.isArray(orig)) {
            orig = [];
          }
          list = orig.concat(value);
          for (k in list) {
            v = list[k];
            if (!v._time) {
              list[k] = {
                _time: settings.time,
                _value: v
              };
            }
          }
          sets[field] = {
            type: '$push',
            value: {
              _time: settings.time,
              _value: value
            }
          };
          setColumn(new_fact, field, list.filter(function(v) {
            return !!v;
          }));
        }
        if (mode === 'oldest') {
          if (typeof old_value === 'undefined') {
            if (sets.$set == null) {
              sets.$set = {};
            }
            sets.$set[field] = value;
            sets[field] = {
              type: '$set',
              value: value
            };
          }
          setColumn(new_fact, field, old_value != null ? old_value : value);
        }
        if (mode === 'min' || mode === 'max') {
          value = Math[mode].apply(null, [value, old_value].map(Number).filter(function(x) {
            return !isNaN(x);
          }));
          sets[field] = {
            type: '$set',
            value: value
          };
          setColumn(new_fact, field, value);
        }
        if (mode === 'push') {
          orig = old_value || [];
          if (!Array.isArray(orig)) {
            orig = [];
          }
          list = orig.concat(value);
          sets[field] = {
            type: '$push',
            value: value
          };
        }
        if (mode === 'push_unique') {
          sets[field] = {
            type: '$addToSet',
            value: value
          };
        }
      }
    }
    return {
      fact: new_fact,
      updates: sets
    };
  };

}).call(this);

/*
//@ sourceMappingURL=merge_facts.map
*/
